// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYJb5AfU7O-cS9hnB_Dk55UE_OIRhkF0',
    appId: '1:539784541658:web:d4c4389df1d47b8156fce3',
    messagingSenderId: '539784541658',
    projectId: 'fluttercollegeproject-9d60e',
    authDomain: 'fluttercollegeproject-9d60e.firebaseapp.com',
    storageBucket: 'fluttercollegeproject-9d60e.firebasestorage.app',
    measurementId: 'G-LY8H8YM6GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD2vZPpFEL2Axi8-8N2bl82Uzo1oabBxE',
    appId: '1:539784541658:android:2ac0226072b9757956fce3',
    messagingSenderId: '539784541658',
    projectId: 'fluttercollegeproject-9d60e',
    storageBucket: 'fluttercollegeproject-9d60e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ7n97IfvjRMQO2ex6-mcDv7ImqxCAhp4',
    appId: '1:539784541658:ios:38137fe23715ee1856fce3',
    messagingSenderId: '539784541658',
    projectId: 'fluttercollegeproject-9d60e',
    storageBucket: 'fluttercollegeproject-9d60e.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ7n97IfvjRMQO2ex6-mcDv7ImqxCAhp4',
    appId: '1:539784541658:ios:38137fe23715ee1856fce3',
    messagingSenderId: '539784541658',
    projectId: 'fluttercollegeproject-9d60e',
    storageBucket: 'fluttercollegeproject-9d60e.firebasestorage.app',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzYJb5AfU7O-cS9hnB_Dk55UE_OIRhkF0',
    appId: '1:539784541658:web:ac4bc378824cf18b56fce3',
    messagingSenderId: '539784541658',
    projectId: 'fluttercollegeproject-9d60e',
    authDomain: 'fluttercollegeproject-9d60e.firebaseapp.com',
    storageBucket: 'fluttercollegeproject-9d60e.firebasestorage.app',
    measurementId: 'G-LLRGR5MXL0',
  );
}
